{"timestamp": "2025-05-12T20:43:23.477992", "question_type": "numeric", "question_text": "how many years of work experience do you have with sql?", "context": "", "job_title": "", "company": "", "job_link": ""}
{"timestamp": "2025-05-12T20:43:51.909273", "job_title": "ðŸ”¹ Lead C# & React Full Stack Developer | Front Office Trading | Paris, France ðŸ‡«ðŸ‡· | â‚¬85,000 - â‚¬95,000 + Bonus | Hybrid (3 days in-office)", "company": "VirtueTech Recruitment Group", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226019187/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:44:29.688127", "job_title": "DÃ©veloppeur Full-Stack Junior", "company": "SEREO Engineering", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4228525308/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:45:04.743950", "job_title": "Senior Software Engineer | Python |Typescript | AWS | Bun | Terraform | Docker | Redis | SQL | NoSQL", "company": "Enigma", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226503741/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:45:43.336466", "question_type": "dropdown", "question_text": "do you have a background in computational chemistry, cheminformatics, computational biology, bioinformatics, data engineering or computer science? \ndo you have a background in computational chemistry, cheminformatics, computational biology, bioinformatics, data engineering or computer science?", "context": "", "job_title": "", "company": "", "job_link": ""}
{"timestamp": "2025-05-12T20:45:47.646054", "question_type": "dropdown", "question_text": "have you been in a data engineer focused role within the last 2 years? \nhave you been in a data engineer focused role within the last 2 years?", "context": "", "job_title": "", "company": "", "job_link": ""}
{"timestamp": "2025-05-12T20:45:56.255490", "question_type": "dropdown", "question_text": "do you have deep expertise working with admet data pipelines for machine learning?\ndo you have deep expertise working with admet data pipelines for machine learning?", "context": "", "job_title": "", "company": "", "job_link": ""}
{"timestamp": "2025-05-12T20:46:28.005685", "job_title": "Senior Data Engineer â€“ ADMET & Pharma Collaborations | Series A - Drug discovery B2B Platform | Fully Remote, EU | Up to Â£130,000", "company": "Owen Thomas | Pending B Corpâ„¢", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4228479167/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:46:36.255402", "job_title": "Senior DÃ©veloppeur Back (Node.js) - H/F", "company": "EY FABERNOVEL", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4225687448/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:46:45.691739", "job_title": "DÃ©veloppeur.se Python", "company": "MERITIS", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4225683659/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:46:54.364482", "job_title": "Senior Python Engineer - Data Platform (Remote)", "company": "Axiom Recruit", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226260410/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:47:03.570034", "job_title": "Data Engineer", "company": "Datatorii", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4225684617/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:47:12.050076", "job_title": "IngÃ©nieur DevOps", "company": "DATASOLUTION - Partner of your digital transformation", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4228439795/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:47:21.315434", "job_title": "DÃ©veloppeur Senior F/H en CDI", "company": "francebillet", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4225685409/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:47:30.836537", "job_title": "IngÃ©nieur Cloud & SystÃ¨mes â€“ Infrastructure AWS", "company": "INFORMATIS TECHNOLOGY SYSTEM", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226257425/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:47:40.405713", "job_title": "IngÃ©nieur Cloud/ DevOps H/F", "company": "kodemade", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226250469/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:48:23.425780", "question_type": "numeric", "question_text": "how many years of work experience do you have with artificial intelligence (ai)?", "context": "", "job_title": "", "company": "", "job_link": ""}
{"timestamp": "2025-05-12T20:48:53.582773", "job_title": "Senior AI Engineer â€“ TechForGood / AI / IoT - 100.000 EUR - Europe/Remote", "company": "Xcede", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226249559/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:49:02.122381", "job_title": "IngÃ©nieur(e) IA GÃ©nÃ©rative F/H", "company": "Up Technologies", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4228437775/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:49:21.106565", "job_title": "Lead Data Engineer H/F", "company": "OVENTI Consulting", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226249137/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:49:21.107957", "job_title": "Lead Data Engineer H/F", "company": "OVENTI Consulting", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226249137/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:49:30.076917", "job_title": "Data engineer", "company": "Lawrence Harvey", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4226249057/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:49:38.534906", "job_title": "DÃ©veloppeur C# client lourd", "company": "Canopee Group", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4225679255/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
{"timestamp": "2025-05-12T20:49:46.808774", "job_title": "Testeur.se QA fonctionnel / automatisation - CDI", "company": "Octopus HACCP", "location": "", "job_link": "https://www.linkedin.com/jobs/view/4228432145/", "status": "success", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 502, in apply_jobs
    job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title--link')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 601, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 361, in start_applying
    self.next_job_page(position, location_url, job_page_number)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 1363, in next_job_page
    self.browser.get("https://www.linkedin.com/jobs/search/" + self.base_search_url +
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     "&keywords=" + position + location + "&start=" + str(job_page * 25))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 361, in start_applying
    self.next_job_page(position, location_url, job_page_number)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 1363, in next_job_page
    self.browser.get("https://www.linkedin.com/jobs/search/" + self.base_search_url +
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     "&keywords=" + position + location + "&start=" + str(job_page * 25))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 361, in start_applying
    self.next_job_page(position, location_url, job_page_number)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 1363, in next_job_page
    self.browser.get("https://www.linkedin.com/jobs/search/" + self.base_search_url +
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     "&keywords=" + position + location + "&start=" + str(job_page * 25))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 361, in start_applying
    self.next_job_page(position, location_url, job_page_number)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 1363, in next_job_page
    self.browser.get("https://www.linkedin.com/jobs/search/" + self.base_search_url +
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     "&keywords=" + position + location + "&start=" + str(job_page * 25))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
	GetHandleVerifier [0x0119FC53+61635]
	GetHandleVerifier [0x0119FC94+61700]
	(No symbol) [0x00FC05D3]
	(No symbol) [0x00F9FBC9]
	(No symbol) [0x01033CBE]
	(No symbol) [0x0104DF19]
	(No symbol) [0x0102D096]
	(No symbol) [0x00FFC840]
	(No symbol) [0x00FFD6A4]
	GetHandleVerifier [0x01424573+2701795]
	GetHandleVerifier [0x0141FCF6+2683238]
	GetHandleVerifier [0x0143AA3E+2793134]
	GetHandleVerifier [0x011B6915+155013]
	GetHandleVerifier [0x011BCFFD+181357]
	GetHandleVerifier [0x011A74A8+92440]
	GetHandleVerifier [0x011A7650+92864]
	GetHandleVerifier [0x01192040+5296]
	BaseThreadInitThunk [0x75935D49+25]
	RtlInitializeExceptionChain [0x7700CFFB+107]
	RtlGetAppContainerNamedObjectPath [0x7700CF81+561]

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\EasyApply\linkedineasyapply.py", line 509, in apply_jobs
    time.sleep(random.uniform(3, 5))
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
", "reason": "", "answers": [], "ai_answers": [], "time_taken_sec": null, "error": null, "screenshot": null}
